INFERANALYZE = '/usr/local/Cellar/infer/0.13.0/lib/infer/infer/bin/infer-analyze' --no-report --results-dir '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.7f73aac2dd5fc4fc138799062b0a34ad
cl1: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.c7ad178feaa43f25d5b11d3ed8950b90
cl2: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/IRadioContract.java.b7592d8e3d2622e2a05fd6720d295478
cl3: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.4a8b79952e3ca5106c0500f148402b3e
cl4: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/PlayerPresenter.java.4af41222ab75dc92a394514dc6517205
cl5: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.0aedf6a38f3af89961b51e48621fb009
cl6: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.bc1f2f3c1f8b0cf80983d650faadc126
cl7: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/IWelcomeContract.java.c06f20890845b60cdf280f7685ea5dcb
cl8: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.4dac68a4a12f16c5b1dd6227bbe85323
cl9: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/Constants.java.a199ab191ce9b6c530d2f2485ccda1cf
cl10: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.d386c3718b07b88a3a44c583aaf1756e
cl11: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/RadioActivity.java.f2f6947262d697e422a7462588eddae8
cl12: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.d6c536f48a190e0ab5599e5440bdaffa
cl13: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl13.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.e81359d13ced8908235a70757a577518
cl14: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl14.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.c94c2e5c9a88d638c61f3916e98e3398
cl15: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl15.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.ca892a4ee249768ea1ffdda1610c4582
cl16: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl16.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl17: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl17.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.0491aee41b2e89ef45d0a9bcaae5b11f
cl18: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl18.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/PlayerActivity.java.b99c4fda4baa5e530a77fa45e9c3bc07
cl19: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl19.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/WelcomePresenter.java.e8de5cd8ea37be57427326b7d0e0a628
cl20: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl20.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.0b9c5aed8f8fd6a9ac20ffc61be84ac2
cl21: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl21.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/IPlayerContract.java.c474bb30ba45d5bb780d460e8c3ddde0
cl22: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl22.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.f22d1cf85f4ae11f8a6b9b949ddc22d0
cl23: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl23.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/NetworkChangeReceiver.java.b1ed7a7cafa8bd3c047b30decf7828f6
cl24: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl24.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.87e344c3d44e2857f1a16ec94bd909ba
cl25: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl25.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/WelcomeActivity.java.493ad305c74ae1beaba90af0b55ba671
cl26: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl26.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/Node.java.fde4807b7f13c45ecc2096b9dc0e4819
cl27: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl27.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.fe74767c8d8df9911c249d4e1ba17b3d
cl28: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl28.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/BuildConfig.java.7f4030cb464d44db04b1058049f65d18
cl29: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl29.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.decf39ede8f0339a51b0975567b00588
cl30: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl30.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/TutorialActivity.java.e2afe9df933eb0ed83db9c4f8e26f44e
cl31: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl31.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.41b49833449da05896ad7b51fc598e50
cl32: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl32.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.24134053bf403b840ea0521f5ea4546d
cl33: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl33.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.2f33a743c7cf9335c5eac78ae599f059
cl34: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl34.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/CommonIntent.java.e387f7e02dfd226cb552fe81fefaf707
cl35: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl35.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/RadioPresenter.java.7cf19d751370a2a4239f0cb41213e65b
cl36: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl36.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/ExampleUnitTest.java.882fd16560d49adf0462bb7a4392d44e
cl37: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl37.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.90ece509924e994d810f8699615472ce
cl38: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl38.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.a9974d014cbe163cd86ab3dc17465606
cl39: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl39.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/FMRadioIndiaApplication.java.463d512dbbd81109f97bfbaa5b5fb7a4
cl40: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl40.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.23d5e8ef9d9a545963f3f4fea567482f
cl41: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl41.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/NodeManager.java.dc62e8a7d4792826619a09cb201cad22
cl42: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl42.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/CloudMessagingService.java.6fdf9ea210d64b4d8635a78f4bcb1797
cl43: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl43.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.3af832ea846dbd7486f6cfcba6b6c4ad
cl44: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl44.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/Manifest.java.9cfb6527fccd00f397a28d8a34671330
cl45: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl45.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.a3a7414bcb671140be079a93f84256a3
cl46: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl46.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.b52479ac4e5053e814143666631cf52d
cl47: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl47.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/AlermReceiver.java.ffdb78a7e164ac0623e933437c71403b
cl48: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl48.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.cb2bafe0063f6b481173ebc187ed4f18
cl49: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl49.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/R.java.ed2872b26942afa5a8f13a8f68c107c1
cl50: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl50.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/Configuration.java.86f7c0b494be184ed0e3b148d81d36e9
cl51: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl51.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/captured/BackgroundMusicPlayService.java.683e4c6eef7ca9f4198bd47b15243a5d
cl52: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/fmradioindia/infer-out/multicore/xcl52.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
