INFERANALYZE = '/usr/local/Cellar/infer/0.13.0/lib/infer/infer/bin/infer-analyze' --no-report --results-dir '/Users/dip/dipankar/androidStudio/ping/client/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 cl53 cl54 cl55 cl56 cl57 cl58 cl59 cl60 cl61 cl62 cl63 cl64 cl65 cl66 cl67 cl68 cl69 cl70 cl71 cl72 cl73 cl74 cl75 cl76 cl77 cl78 cl79 cl80 cl81 cl82 cl83 cl84 cl85 cl86 cl87 cl88 cl89 cl90 cl91 cl92 cl93 cl94 cl95 cl96 cl97 cl98 cl99 cl100 cl101 cl102 cl103 cl104 cl105 cl106 cl107 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/LoginActivity.java.3469b473b4ea46a273975a95db75b0f7
cl1: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ExampleUnitTest.java.d24fc18ac91dc261502eefe9e13b2d93
cl2: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SearchPresenter.java.7506020422ad500d1e32e3acb80d091b
cl3: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.9b59db7bc2b8d535b08868ed283ea4dc
cl4: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ScreenCapturerAndroid.java.27c03a78754655d671ee7a3fc0e35e6e
cl5: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.209538407390effebc99ddca43aaec76
cl6: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CameraSession.java.0eb9a49185e8942587048598ce2122a6
cl7: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/PingApplication.java.6aa437ad3616afd2eb55dff3bb3013a0
cl8: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/WebRtcUtils.java.2752aa445c7a57e5902818b7e5f1c263
cl9: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.4a8b79952e3ca5106c0500f148402b3e
cl10: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RtcDeviceInfo.java.2cf512a6c597828625af2cb0bfb25c1f
cl11: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ViewletPeerInfoVideo.java.46b96a18c555823dbc66e91fe33c471d
cl12: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CapturerObserverProxy.java.05642edb6061baf3d9b33e7b76226b5e
cl13: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl13.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/QuickContactAdapter.java.bc1d027acc9d65aec9c5bc71ae88898f
cl14: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl14.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.4dac68a4a12f16c5b1dd6227bbe85323
cl15: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl15.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/HomePresenter.java.81585a913a860a66f73e7b0d3af3a8fb
cl16: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl16.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IRtcEngine.java.9223743b99dfd774ad3c3c2a3a2feede
cl17: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl17.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Camera1Session.java.d3a4ccb781615d464851c3d2e160a2cd
cl18: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl18.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.401f656de18c73d29fed681664dc2a14
cl19: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl19.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.26b52aa9ebdabe75f439651e8212661e
cl20: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl20.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IRtcDeviceInfo.java.6f65d37146418c4881e2382331e84f21
cl21: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl21.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SearchActivity.java.4e2997921b7604211837815f0a91bff7
cl22: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl22.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Camera1Enumerator.java.b070993af19d4465da61e5dbfb63d5d1
cl23: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl23.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Utils.java.ac8261b0658c341280efd8326dedf44b
cl24: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl24.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SocketIOSignaling.java.de65475f522fb6be613b26adf7b4451d
cl25: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl25.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RtcUser.java.71c03ddbc2b053d4259f6c3f3cc7d3ff
cl26: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl26.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RTCVideoEffector.java.916b59974bda99f0154d325685d6c84f
cl27: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl27.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IHome.java.9275dbe3eff566b710e5a387c6adf51c
cl28: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl28.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.c94c2e5c9a88d638c61f3916e98e3398
cl29: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl29.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.8dbd35eea881889e635e6789ba28fb68
cl30: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl30.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/BitMapUtils.java.883348df2807bfea73c51e47969a26ef
cl31: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl31.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/DataUsesReporter.java.18f3654db8c83b7b291a16176168f30b
cl32: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl32.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ContactManger.java.8f8a64636436fd5422e7eabee1c3a0d5
cl33: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl33.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RecyclerTouchListener.java.1b0411e93515af81735202a0e8cbb736
cl34: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl34.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.e0d90f791a022b1cae482ba1000dfd91
cl35: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl35.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ca25520ea4da1383082001d482539c58
cl36: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl36.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.f1106c2269bd19c8e30f5969529b3eeb
cl37: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl37.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ca892a4ee249768ea1ffdda1610c4582
cl38: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl38.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.c1785485834e7e6477e4045a2debc92b
cl39: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl39.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl40: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl40.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.0491aee41b2e89ef45d0a9bcaae5b11f
cl41: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl41.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallIncomingPageView.java.af7e0894bb0a1b6c515361d69a0dacad
cl42: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl42.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IMultiVideoPane.java.25a4c6a05b90c36d40555628d1961fa9
cl43: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl43.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.d910afd42bd9a8d6eb1ac39285dd05ca
cl44: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl44.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CustomButtonSheetView.java.bc41af9153a9b049013a7d34b48e6b6b
cl45: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl45.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/AudioManagerUtils.java.992b3aebaffe16ec5773e559129c9767
cl46: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl46.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/MyFirebaseInstanceIDService.java.752fe32483d2018be16e277509d8aeba
cl47: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl47.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ExtendedSurfaceView.java.b11064fef8e9a51c59294e3a58b5fac3
cl48: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl48.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IContactManager.java.35c730b9a8782cc9013e0a7efea3fbe6
cl49: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl49.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.522ae289e8ce3dd94bfadc61277fa057
cl50: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl50.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RecentCallAdapter.java.f44b5cd68d1f1f03515b6dd9fdbedf32
cl51: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl51.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ICallSignalingApi.java.3a3c700b17f2e29ff626507b6027118f
cl52: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl52.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.80637489829c513051c4cb28ff71dd22
cl53: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl53.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ddca3e232828e4ea0d293ebde02d6370
cl54: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl54.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ICallInfo.java.4f1c8528d6ce70237d9fa9b55b7d39de
cl55: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl55.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.dc0438f1923ed2328b09ae8c9e3b9cbe
cl56: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl56.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallOutgoingPageView.java.670bd13cee854a2b4fd36d8bbf41b59d
cl57: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl57.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.fe74767c8d8df9911c249d4e1ba17b3d
cl58: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl58.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallActivity.java.449f7307d556113a775ab3df97840a12
cl59: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl59.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/FileVideoCapturer.java.090eeaffaab5184b213115d775533c2c
cl60: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl60.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.decf39ede8f0339a51b0975567b00588
cl61: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl61.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.41b49833449da05896ad7b51fc598e50
cl62: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl62.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ff0a530851fd33693fa8b9c3cdf8e4d7
cl63: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl63.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Configuration.java.c5a94ad2c853dd94979ae6371617fdc5
cl64: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl64.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/HomeActivity.java.403278895f4ac40f29c10b965a314239
cl65: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl65.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.e372a5d3b5b15a356a7c59e038b3446e
cl66: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl66.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/EffectCamera1Capturer.java.fbf5add66ea111bfbecd3625b927632c
cl67: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl67.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IPushNotification.java.156daa3f4f5c0d147e2513694369a621
cl68: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl68.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.7096d8eddf06968c8fc7754299301751
cl69: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl69.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IAddOn.java.e5dbcba67cd88d4cc95153828f46e0c8
cl70: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl70.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RecentUserAdapter.java.66d591ea397a0a6fbd4766617de64aeb
cl71: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl71.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.42662577c7b6d5919f8f40c8e992f058
cl72: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl72.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.a9974d014cbe163cd86ab3dc17465606
cl73: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl73.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallHistoryAdapter.java.638565bb34758b16c8a6208842b8a25d
cl74: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl74.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Constant.java.f531d414af83de8a52c0e16572509542
cl75: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl75.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.23d5e8ef9d9a545963f3f4fea567482f
cl76: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl76.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/BaseAddonView.java.f07c3c9dc6649839507aab1d0322d450
cl77: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl77.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallEndedPageView.java.681eed5742d997a496683bd5193299c1
cl78: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl78.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.88e57cf466948ef224e763932012f5f7
cl79: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl79.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ViewletPeerInfoAudio.java.48a5957608a2fea70a495746b75c47d1
cl80: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl80.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.3af832ea846dbd7486f6cfcba6b6c4ad
cl81: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl81.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Histogram.java.04629a04847d95cba06c60acee644f4c
cl82: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl82.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallLandingPageView.java.37afe38de394a0fda23a3daa57fe05e5
cl83: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl83.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.a3a7414bcb671140be079a93f84256a3
cl84: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl84.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/BuildConfig.java.12fa01e95a4b7a2d761e5f62ace29ed7
cl85: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl85.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/WebRtcEngine2.java.2fdededbc72de7e51d1a178caccfb1ae
cl86: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl86.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/AcceptRejectNotification.java.dce43d96b6e0081e9964fa91fde1c8db
cl87: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl87.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.2280001835827ea2a2585ca55f2f8741
cl88: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl88.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallOngoingPageView.java.d7741833c8530ce499624703f6f8cb7b
cl89: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl89.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IRtcUser.java.225f153b34ee6e2a494f35a1ee2571e7
cl90: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl90.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CameraCapturer.java.c672d1d65d9378a717bbe33416d27650
cl91: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl91.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.b52479ac4e5053e814143666631cf52d
cl92: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl92.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/MediaPlayer.java.860c17121fca9f991f8f28492a6a9a9e
cl93: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl93.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Manifest.java.75d780b365acc5d5ce519628d13eef22
cl94: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl94.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.70c1366e9a88c88d0e510a35dda180ca
cl95: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl95.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ICallPage.java.972a55113e11a41ffc7bb6ad767dc38e
cl96: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl96.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ISearch.java.18c647b9376d259d70a3a4ef67044ca6
cl97: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl97.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallPresenter.java.ca67f75dce6af96ed7d378adfc067477
cl98: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl98.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ed2872b26942afa5a8f13a8f68c107c1
cl99: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl99.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SheetItem.java.4406bf975f874b18eed54df8fb9547fd
cl100: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl100.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/MyFirebaseMessagingService.java.ac97635e4ceafe0b4e5e9b4e15f130a8
cl101: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl101.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallVideoGridView.java.b2b7d5d363aec42aaf01611b4b9c7a70
cl102: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl102.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ContactListAdapter.java.ce7bb77d6a17b5627214be016bfb16d5
cl103: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl103.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Camera1Capturer.java.6dc20b99947c080fca5cc62befed985a
cl104: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl104.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RtcStatView.java.e45efb2d9beedd153567a4bea0fe74b6
cl105: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl105.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallInfo.java.65c79ad25cbf29ef3d5395b4248c51ce
cl106: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl106.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/EffectCamera1Enumerator.java.de7ab3b007c412845493463ccb3b2936
cl107: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl107.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
