INFERANALYZE = '/usr/local/Cellar/infer/0.13.0/lib/infer/infer/bin/infer-analyze' --no-report --results-dir '/Users/dip/dipankar/androidStudio/ping/client/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 cl53 cl54 cl55 cl56 cl57 cl58 cl59 cl60 cl61 cl62 cl63 cl64 cl65 cl66 cl67 cl68 cl69 cl70 cl71 cl72 cl73 cl74 cl75 cl76 cl77 cl78 cl79 cl80 cl81 cl82 cl83 cl84 cl85 cl86 cl87 cl88 cl89 cl90 cl91 cl92 cl93 cl94 cl95 cl96 cl97 cl98 cl99 cl100 cl101 cl102 cl103 cl104 cl105 cl106 cl107 cl108 cl109 cl110 cl111 cl112 cl113 cl114 cl115 cl116 cl117 cl118 cl119 cl120 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/MyFirebaseMessagingService.java.23c4e7e6e02ab7ecd02497c2850424de
cl1: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/WebRtcUtils.java.6fbf95c98e13e4ea72b09c8f2a20fa7a
cl2: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RecentUserAdapter.java.b5fa6ad51c591462274c8dee5b3f4609
cl3: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.9b59db7bc2b8d535b08868ed283ea4dc
cl4: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.209538407390effebc99ddca43aaec76
cl5: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/MapAddonView.java.232d2f79027c5ff1ecadaf912f4225c5
cl6: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/QuickContactAdapter.java.08645ad49a20838da5c091377d91de68
cl7: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Duration.java.12d444c8d63333b48599b9aa2bac9eb8
cl8: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallLandingPageView.java.59141c8418ae886a6f83f3cb8acfd8f2
cl9: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.4a8b79952e3ca5106c0500f148402b3e
cl10: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CapturerObserverProxy.java.049f0250f8a923440ef5edae2219a1dc
cl11: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/LoginActivity.java.356a47f9755efe7bbc3b7ad9defceefd
cl12: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/DirectionFinder.java.4c0c5b316e0effc6be9a687be789dd02
cl13: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl13.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/AudioManagerUtils.java.73339e53e49a5c23d031cc230cfe8619
cl14: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl14.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ICallPage.java.c1aa345a4d1d2063d85903fc1a678d40
cl15: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl15.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Camera1Session.java.9d2f4bf076132a47715c7a1769a79084
cl16: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl16.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IRtcUser.java.f7d3de1c614527ca28eed4e35ed58e8c
cl17: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl17.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Histogram.java.aa2fc0f208e6eb7d2b4e660265c4b677
cl18: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl18.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SocketIOSignaling.java.24ab677e40cb6f4beba94df77725c1e8
cl19: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl19.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Constant.java.198bb3883c497f487e4b5d4823a382be
cl20: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl20.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallOutgoingPageView.java.f5fec3534d289a7db5fb0ee07e44831a
cl21: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl21.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.4dac68a4a12f16c5b1dd6227bbe85323
cl22: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl22.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ScreenCapturerAndroid.java.e3df150683ef0a29e7812a764587c44f
cl23: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl23.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/TestActivity.java.171e1f9aecbbc03a590b4cbcb5448cce
cl24: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl24.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Route.java.9b652ed1354a2d446a86a2ef27404147
cl25: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl25.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.401f656de18c73d29fed681664dc2a14
cl26: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl26.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.26b52aa9ebdabe75f439651e8212661e
cl27: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl27.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RecyclerTouchListener.java.6b7e5c26db3dccc0a5d07418ef697c9a
cl28: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl28.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallVideoGridView.java.bb5056b9b61753919b2b1f75ab191cb9
cl29: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl29.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/EffectCamera1Capturer.java.a2509b461f00dc9183e1c03f9921f3ce
cl30: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl30.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IRtcEngine.java.c14b531676d9a8ba807a50a8b1ab65d8
cl31: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl31.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.c94c2e5c9a88d638c61f3916e98e3398
cl32: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl32.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/MyFirebaseInstanceIDService.java.4675bccee788ac1a996839b1eefc1d0a
cl33: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl33.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.8dbd35eea881889e635e6789ba28fb68
cl34: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl34.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/WebRtcEngine2.java.ccbb27b86c4d0d05cbb8ac643c49fb2d
cl35: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl35.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Camera1Capturer.java.2a510ba6908a3e2a980eda14ebed38bb
cl36: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl36.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ce4ec20fe7565f0566ecc4e51fea66a9
cl37: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl37.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.e0d90f791a022b1cae482ba1000dfd91
cl38: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl38.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/PingApplication.java.c791c9a6d4a255b24622581dcb953ebc
cl39: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl39.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ca25520ea4da1383082001d482539c58
cl40: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl40.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.f1106c2269bd19c8e30f5969529b3eeb
cl41: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl41.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ca892a4ee249768ea1ffdda1610c4582
cl42: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl42.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.c1785485834e7e6477e4045a2debc92b
cl43: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl43.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl44: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl44.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.0491aee41b2e89ef45d0a9bcaae5b11f
cl45: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl45.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.d910afd42bd9a8d6eb1ac39285dd05ca
cl46: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl46.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CameraCapturer.java.c3b0fa427b3568a8cd65625770e6048d
cl47: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl47.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RtcDeviceInfo.java.52095b75675ee4bbb5129b5fd22086ba
cl48: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl48.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.f22d1cf85f4ae11f8a6b9b949ddc22d0
cl49: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl49.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.991d87afbd6e7f37a7860707c2960272
cl50: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl50.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.522ae289e8ce3dd94bfadc61277fa057
cl51: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl51.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/EffectCamera1Enumerator.java.93c7eb24449a34cc7eb7ef6e64fdbecf
cl52: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl52.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CameraSession.java.f54f7efbc198fb2b5949e0168713a6c6
cl53: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl53.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SettingActivity.java.78f7ed81a7e963f1695611690b41a2cf
cl54: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl54.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/HomePresenter.java.030abdf44d7d3bb7887e9246e52c29da
cl55: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl55.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.80637489829c513051c4cb28ff71dd22
cl56: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl56.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ddca3e232828e4ea0d293ebde02d6370
cl57: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl57.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/HomeActivity.java.6a53ec90cc8a722555adbb7c72808cb5
cl58: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl58.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Utils.java.5790f65d30bd923eed0b4696886e7b7b
cl59: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl59.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/DataUsesReporter.java.e17a0034090b473eb43de2376be023b2
cl60: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl60.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallEndedPageView.java.e1fe0622453e73deaac4c7d4bbd7fae2
cl61: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl61.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.dc0438f1923ed2328b09ae8c9e3b9cbe
cl62: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl62.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.fe74767c8d8df9911c249d4e1ba17b3d
cl63: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl63.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Manifest.java.a23c002cbb2b9930f0f7ca768736463a
cl64: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl64.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Distance.java.719da58a847fd11602e41067785bc9bf
cl65: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl65.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallInfo.java.704372f00e9da18064b1d333adc0434a
cl66: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl66.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.decf39ede8f0339a51b0975567b00588
cl67: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl67.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.41b49833449da05896ad7b51fc598e50
cl68: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl68.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.e372a5d3b5b15a356a7c59e038b3446e
cl69: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl69.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.7096d8eddf06968c8fc7754299301751
cl70: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl70.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallOngoingPageView.java.53aa6ab144debc0a622416ba0f7d479e
cl71: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl71.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ExtendedSurfaceView.java.610354aee6ca62bcf1e8c8812f144664
cl72: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl72.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/BuildConfig.java.4e0a9af7fc596a0347742d8e4470bd58
cl73: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl73.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ViewletPeerInfoVideo.java.5d6f10112b37b2e8b9204739ac134c04
cl74: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl74.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.93472957e17894cf526c26e289392e37
cl75: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl75.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/PlaceAutocompleteAdapter.java.fcf4e206013d876cb674094f424604d3
cl76: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl76.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ContactListAdapter.java.051d6c364c8fa4a2504ceb780a3a5198
cl77: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl77.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.42662577c7b6d5919f8f40c8e992f058
cl78: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl78.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SearchActivity.java.7194d28dd72338a7c18b4b13cb09260e
cl79: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl79.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.a9974d014cbe163cd86ab3dc17465606
cl80: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl80.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ICallInfo.java.eb4e3323e5e2682fc81ef506dc284b15
cl81: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl81.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.23d5e8ef9d9a545963f3f4fea567482f
cl82: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl82.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IContactManager.java.bdfcf0c6bd742a27352277ecf506c9a2
cl83: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl83.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ExampleUnitTest.java.db37a048b1ebfa612dba9f3149a66d23
cl84: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl84.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.88e57cf466948ef224e763932012f5f7
cl85: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl85.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.3af832ea846dbd7486f6cfcba6b6c4ad
cl86: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl86.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IPushNotification.java.ffa11f87665f06903f6863e7695a0c66
cl87: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl87.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RtcUser.java.ac412f69b200eb09b10a4d39b2bf4a04
cl88: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl88.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IMultiVideoPane.java.400b2c771b4f87b3fe621273e92307c4
cl89: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl89.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RtcStatView.java.3cc1c8267737611bf124ba79cc8539a5
cl90: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl90.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/BaseAddonView.java.8af5a643eae39ef7f8e8dfba764d6236
cl91: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl91.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallPresenter.java.7b83ca4b3198253ba76b65f24638b843
cl92: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl92.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Camera1Enumerator.java.4b9554d1a7b0a13b401b4a5cbb3ae115
cl93: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl93.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallHistoryAdapter.java.7c1bec28c201322d19fee128b73b25dd
cl94: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl94.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.a3a7414bcb671140be079a93f84256a3
cl95: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl95.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SearchPresenter.java.b0df0e5841b9461c89043630ab2d47af
cl96: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl96.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ViewletPeerInfoAudio.java.40435178e93a9498c75af0a09864287e
cl97: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl97.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Prefernces.java.a3cc4eb0a0ac67df3d7274f7f4331738
cl98: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl98.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CustomButtonSheetView.java.2e3089694c40b3fcf687368bb1e9de9c
cl99: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl99.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.2280001835827ea2a2585ca55f2f8741
cl100: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl100.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IHome.java.dec8f2c73295df18a4e2abbe523baa2f
cl101: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl101.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ICallSignalingApi.java.cdfb5a8ddc5acfbdd2aa80396c9ac5d4
cl102: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl102.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IDirectionFinder.java.72f1d1d6bb7a89f75e91e3bdd10adcdc
cl103: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl103.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallActivity.java.03b4d18ab7c92455e825b4f196d3cca5
cl104: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl104.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.b52479ac4e5053e814143666631cf52d
cl105: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl105.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ContactManger.java.1048ee372b3a4e7e147549d86f22b512
cl106: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl106.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.70c1366e9a88c88d0e510a35dda180ca
cl107: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl107.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/MediaPlayer.java.1399870532f3f2ab97ce7a04edb3de41
cl108: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl108.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IAddOn.java.2df0acb1947926d1f9c0022d2bf28bac
cl109: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl109.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/FileVideoCapturer.java.e0fe5e9bc88f14fc2991dbe4b2342f1e
cl110: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl110.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/ISearch.java.dfd04710c4fcf3290477b90f39318574
cl111: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl111.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/R.java.ed2872b26942afa5a8f13a8f68c107c1
cl112: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl112.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RTCVideoEffector.java.05b02ab1fc6fe28152baddd3302588ce
cl113: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl113.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/RecentCallAdapter.java.f2abe0c4093984a5bb8ce740e2365f62
cl114: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl114.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/SheetItem.java.211c8bb1572dcb3a9784115c88b9daac
cl115: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl115.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/CallIncomingPageView.java.d624e33e76d21600c1a48a5e6f7fc9e0
cl116: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl116.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/AcceptRejectNotification.java.87be162bd405f1f411127c12e5740b42
cl117: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl117.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/IRtcDeviceInfo.java.09349ab2e460bf30e258d2ed57b8e117
cl118: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl118.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/BitMapUtils.java.8422eb07a27c5de5c1098a97afb02345
cl119: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl119.cluster'
	@touch $@

#/Users/dip/dipankar/androidStudio/ping/client/infer-out/captured/Configuration.java.59fa7e88fd431cf5833106386eb55186
cl120: 
	@$(INFERANALYZE) --cluster '/Users/dip/dipankar/androidStudio/ping/client/infer-out/multicore/xcl120.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
