package in.co.dipankar.fmradio.ui.base;

public enum Screen {
  SPLASH_SCREEN,
  HOME_SCREEN,
  LOGIN_SCREEN,
  PLAYER_SCREEN,
  SETTING_SCREEN,
  SEARCH_SCREEN,
  FTUX_SCREEN,
  VIDEO_PLAER_SCREEN,
  CATEGORIES_SCREEN,
}
